version: '3'

services:
  sfm-backend:
      container_name: sfm-backend
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "${SFM_BACKEND_PORT}:${SFM_BACKEND_PORT}"
      environment:
        SFM_FRONTEND_PORT: ${SFM_FRONTEND_PORT:-3000}
        JWT_SECRET: ${JWT_SECRET:-default-secret}
        JWT_MAX_AGE: ${JWT_MAX_AGE:-3600}
        MONGO_ROOT_USER: ${MONGO_ROOT_USER}
        MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        MONGO_HOST: ${MONGO_HOST}
        MONGO_DB_NAME: ${MONGO_DB_NAME}
  
  mongo:
    image: mongo:4.4.20-rc0
    restart: always
    volumes:
      - ./db:/data/db
    networks:
      - express-mongo
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
        
  mongo-express:
    image: mongo-express:1.0.0-20
    restart: always
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
      - PORT=${MONGOEXPRESS_PORT}
    ports:
      - "${MONGOEXPRESS_PORT}:${MONGOEXPRESS_PORT}"
    networks:
      - express-mongo

networks:
  express-mongo:

      